// Auto-generated from docs/audits/ui-api-wiring-audit-2026-02-19.csv
// Do not edit manually; update via scripts/ui-api-wiring-audit.mjs tooling.

export type UiApiResolutionStatus =
  | 'wired_to_existing_api'
  | 'wired_to_navigation_or_state'
  | 'guarded_todo_api';

export interface UiApiResolutionRecord {
  id: string;
  route: string;
  uiLocation: string;
  gapType: string;
  currentBehavior: string;
  file: string;
  line: number;
  status: UiApiResolutionStatus;
}

export const uiApiResolutionRegistry: Record<string, UiApiResolutionRecord> = {
  'ui-api-001': {
    id: 'ui-api-001',
    route: "/documents",
    uiLocation: "Document preview URL resolver",
    gapType: "mock_fallback",
    currentBehavior: "Synchronous preview URL helper always falls back to mock URL.",
    file: "/Users/thunderstruck/Code Playground/vestledger-platform/apps/vestledger-ui/src/services/documentsService.ts",
    line: 417,
    status: 'guarded_todo_api',
  },
  'ui-api-002': {
    id: 'ui-api-002',
    route: "/documents",
    uiLocation: "Document preview model mapping",
    gapType: "empty_state",
    currentBehavior: "Preview mapping uses mock URLs only in demo mode; API mode marks missing URLs as unavailable previews.",
    file: "/Users/thunderstruck/Code Playground/vestledger-platform/apps/vestledger-ui/src/components/documents/index.tsx",
    line: 81,
    status: 'guarded_todo_api',
  },
  'ui-api-003': {
    id: 'ui-api-003',
    route: "/documents",
    uiLocation: "Document manager move callback",
    gapType: "no_handler",
    currentBehavior: "Move callback prop is accepted but intentionally ignored as _onMoveDocument.",
    file: "/Users/thunderstruck/Code Playground/vestledger-platform/apps/vestledger-ui/src/components/documents/document-manager.tsx",
    line: 154,
    status: 'guarded_todo_api',
  },
  'ui-api-004': {
    id: 'ui-api-004',
    route: "/documents",
    uiLocation: "Document manager access callback",
    gapType: "no_handler",
    currentBehavior: "Access-level callback prop is accepted but intentionally ignored as _onUpdateAccess.",
    file: "/Users/thunderstruck/Code Playground/vestledger-platform/apps/vestledger-ui/src/components/documents/document-manager.tsx",
    line: 155,
    status: 'guarded_todo_api',
  },
  'ui-api-005': {
    id: 'ui-api-005',
    route: "/documents",
    uiLocation: "Folder cards",
    gapType: "no_handler",
    currentBehavior: "Folder cards render as buttons without open-folder action.",
    file: "/Users/thunderstruck/Code Playground/vestledger-platform/apps/vestledger-ui/src/components/documents/document-manager.tsx",
    line: 470,
    status: 'guarded_todo_api',
  },
  'ui-api-006': {
    id: 'ui-api-006',
    route: "/lp-management",
    uiLocation: "Bulk send report",
    gapType: "local_only",
    currentBehavior: "Returns local recipient count and timestamp; no backend mutation call.",
    file: "/Users/thunderstruck/Code Playground/vestledger-platform/apps/vestledger-ui/src/services/lpPortal/lpManagementService.ts",
    line: 343,
    status: 'guarded_todo_api',
  },
  'ui-api-007': {
    id: 'ui-api-007',
    route: "/lp-management",
    uiLocation: "Bulk send capital call",
    gapType: "local_only",
    currentBehavior: "Returns local recipient count and timestamp; no backend mutation call.",
    file: "/Users/thunderstruck/Code Playground/vestledger-platform/apps/vestledger-ui/src/services/lpPortal/lpManagementService.ts",
    line: 351,
    status: 'guarded_todo_api',
  },
  'ui-api-008': {
    id: 'ui-api-008',
    route: "/lp-management",
    uiLocation: "Send LP update",
    gapType: "local_only",
    currentBehavior: "Returns local recipient count and timestamp; no backend mutation call.",
    file: "/Users/thunderstruck/Code Playground/vestledger-platform/apps/vestledger-ui/src/services/lpPortal/lpManagementService.ts",
    line: 390,
    status: 'guarded_todo_api',
  },
  'ui-api-009': {
    id: 'ui-api-009',
    route: "/lp-management",
    uiLocation: "Export LP data",
    gapType: "local_only",
    currentBehavior: "Constructs local export metadata without backend export job.",
    file: "/Users/thunderstruck/Code Playground/vestledger-platform/apps/vestledger-ui/src/services/lpPortal/lpManagementService.ts",
    line: 359,
    status: 'guarded_todo_api',
  },
  'ui-api-010': {
    id: 'ui-api-010',
    route: "/lp-management",
    uiLocation: "Generate LP report",
    gapType: "local_only",
    currentBehavior: "Creates draft report and upserts it in local cache.",
    file: "/Users/thunderstruck/Code Playground/vestledger-platform/apps/vestledger-ui/src/services/lpPortal/lpManagementService.ts",
    line: 370,
    status: 'guarded_todo_api',
  },
  'ui-api-011': {
    id: 'ui-api-011',
    route: "/lp-management",
    uiLocation: "Published report card actions",
    gapType: "no_handler",
    currentBehavior: "View, Download, Share, and Edit Draft buttons have no action handler.",
    file: "/Users/thunderstruck/Code Playground/vestledger-platform/apps/vestledger-ui/src/components/lp-portal/lp-management.tsx",
    line: 425,
    status: 'guarded_todo_api',
  },
  'ui-api-012': {
    id: 'ui-api-012',
    route: "/lp-management",
    uiLocation: "Initial snapshot data",
    gapType: "empty_state",
    currentBehavior: "Base snapshot seeds LP management data only in demo mode; API mode resolves from cache or empty state.",
    file: "/Users/thunderstruck/Code Playground/vestledger-platform/apps/vestledger-ui/src/services/lpPortal/lpManagementService.ts",
    line: 256,
    status: 'guarded_todo_api',
  },
  'ui-api-013': {
    id: 'ui-api-013',
    route: "/lp-portal",
    uiLocation: "Investor snapshot baseline",
    gapType: "empty_state",
    currentBehavior: "Investor snapshot seeds from mocks only in demo mode; API mode resolves from cache or empty state.",
    file: "/Users/thunderstruck/Code Playground/vestledger-platform/apps/vestledger-ui/src/services/lpPortal/lpInvestorPortalService.ts",
    line: 49,
    status: 'guarded_todo_api',
  },
  'ui-api-014': {
    id: 'ui-api-014',
    route: "/lp-portal",
    uiLocation: "Reports tab download action",
    gapType: "no_handler",
    currentBehavior: "Quarterly report download button has no handler.",
    file: "/Users/thunderstruck/Code Playground/vestledger-platform/apps/vestledger-ui/src/components/lp-portal/lp-investor-portal.tsx",
    line: 192,
    status: 'guarded_todo_api',
  },
  'ui-api-015': {
    id: 'ui-api-015',
    route: "/lp-portal",
    uiLocation: "Statements bulk actions",
    gapType: "no_handler",
    currentBehavior: "Download All, Email All, and Print All buttons have no handlers.",
    file: "/Users/thunderstruck/Code Playground/vestledger-platform/apps/vestledger-ui/src/components/lp-portal/distribution-statements.tsx",
    line: 58,
    status: 'guarded_todo_api',
  },
  'ui-api-016': {
    id: 'ui-api-016',
    route: "/lp-portal",
    uiLocation: "Statement download button",
    gapType: "no_handler",
    currentBehavior: "Per-statement Download button has no handler.",
    file: "/Users/thunderstruck/Code Playground/vestledger-platform/apps/vestledger-ui/src/components/lp-portal/distribution-statements.tsx",
    line: 106,
    status: 'guarded_todo_api',
  },
  'ui-api-017': {
    id: 'ui-api-017',
    route: "/lp-portal",
    uiLocation: "Statement preview URL",
    gapType: "empty_state",
    currentBehavior: "Statement preview uses mock PDFs only in demo mode; API mode leaves missing PDFs in unavailable-preview state.",
    file: "/Users/thunderstruck/Code Playground/vestledger-platform/apps/vestledger-ui/src/components/lp-portal/distribution-statements.tsx",
    line: 25,
    status: 'guarded_todo_api',
  },
  'ui-api-018': {
    id: 'ui-api-018',
    route: "/lp-portal",
    uiLocation: "Upcoming distribution details",
    gapType: "no_handler",
    currentBehavior: "Details button has no handler.",
    file: "/Users/thunderstruck/Code Playground/vestledger-platform/apps/vestledger-ui/src/components/lp-portal/distribution-upcoming.tsx",
    line: 152,
    status: 'guarded_todo_api',
  },
  'ui-api-019': {
    id: 'ui-api-019',
    route: "/lp-portal",
    uiLocation: "Notification preferences save",
    gapType: "local_only",
    currentBehavior: "Save sets local saved flag only.",
    file: "/Users/thunderstruck/Code Playground/vestledger-platform/apps/vestledger-ui/src/components/lp-portal/distribution-preferences.tsx",
    line: 27,
    status: 'guarded_todo_api',
  },
  'ui-api-020': {
    id: 'ui-api-020',
    route: "/lp-portal",
    uiLocation: "Bank details save",
    gapType: "local_only",
    currentBehavior: "Save performs local validation/state updates only.",
    file: "/Users/thunderstruck/Code Playground/vestledger-platform/apps/vestledger-ui/src/components/lp-portal/bank-details-form.tsx",
    line: 44,
    status: 'guarded_todo_api',
  },
  'ui-api-021': {
    id: 'ui-api-021',
    route: "/lp-portal",
    uiLocation: "Distribution confirmations",
    gapType: "local_only",
    currentBehavior: "Confirm Receipt updates local confirmedIds set only.",
    file: "/Users/thunderstruck/Code Playground/vestledger-platform/apps/vestledger-ui/src/components/lp-portal/distribution-confirmation.tsx",
    line: 15,
    status: 'guarded_todo_api',
  },
  'ui-api-022': {
    id: 'ui-api-022',
    route: "/lp-portal",
    uiLocation: "Distribution elections",
    gapType: "local_only",
    currentBehavior: "Submit updates local submittedIds set only.",
    file: "/Users/thunderstruck/Code Playground/vestledger-platform/apps/vestledger-ui/src/components/lp-portal/distribution-elections.tsx",
    line: 34,
    status: 'guarded_todo_api',
  },
  'ui-api-023': {
    id: 'ui-api-023',
    route: "/analytics",
    uiLocation: "Page header AI summary",
    gapType: "hardcoded",
    currentBehavior: "Header AI summary text is static narrative, not API-fed.",
    file: "/Users/thunderstruck/Code Playground/vestledger-platform/apps/vestledger-ui/src/components/analytics.tsx",
    line: 55,
    status: 'guarded_todo_api',
  },
  'ui-api-024': {
    id: 'ui-api-024',
    route: "/analytics",
    uiLocation: "All-funds snapshot path",
    gapType: "empty_state",
    currentBehavior: "All-funds snapshot resolves from cached API data or empty state; mock seeds are demo-only.",
    file: "/Users/thunderstruck/Code Playground/vestledger-platform/apps/vestledger-ui/src/services/analytics/fundAnalyticsService.ts",
    line: 437,
    status: 'guarded_todo_api',
  },
  'ui-api-025': {
    id: 'ui-api-025',
    route: "/analytics",
    uiLocation: "Read snapshot fallback",
    gapType: "empty_state",
    currentBehavior: "Reader returns cached/latest API snapshot or empty state; mock seeds are demo-only.",
    file: "/Users/thunderstruck/Code Playground/vestledger-platform/apps/vestledger-ui/src/services/analytics/fundAnalyticsService.ts",
    line: 419,
    status: 'guarded_todo_api',
  },
  'ui-api-026': {
    id: 'ui-api-026',
    route: "/dealflow-review",
    uiLocation: "Review slide source",
    gapType: "mock_always",
    currentBehavior: "Slides are always generated from mock slide builder.",
    file: "/Users/thunderstruck/Code Playground/vestledger-platform/apps/vestledger-ui/src/services/dealflow/dealflowReviewService.ts",
    line: 147,
    status: 'guarded_todo_api',
  },
  'ui-api-027': {
    id: 'ui-api-027',
    route: "/dealflow-review",
    uiLocation: "Voting state persistence",
    gapType: "local_only",
    currentBehavior: "Votes and vote metadata are stored in UI keys only.",
    file: "/Users/thunderstruck/Code Playground/vestledger-platform/apps/vestledger-ui/src/components/dealflow/dealflow-review.tsx",
    line: 42,
    status: 'guarded_todo_api',
  },
  'ui-api-028': {
    id: 'ui-api-028',
    route: "/dealflow-review",
    uiLocation: "Presentation mode state",
    gapType: "local_only",
    currentBehavior: "Presentation toggle state is local UI key only.",
    file: "/Users/thunderstruck/Code Playground/vestledger-platform/apps/vestledger-ui/src/components/dealflow/dealflow-review.tsx",
    line: 41,
    status: 'guarded_todo_api',
  },
  'ui-api-029': {
    id: 'ui-api-029',
    route: "/dealflow-review",
    uiLocation: "Export flow",
    gapType: "client_only",
    currentBehavior: "Export creates and downloads client-side JSON blob.",
    file: "/Users/thunderstruck/Code Playground/vestledger-platform/apps/vestledger-ui/src/components/dealflow/dealflow-review.tsx",
    line: 373,
    status: 'guarded_todo_api',
  },
  'ui-api-030': {
    id: 'ui-api-030',
    route: "/dealflow-review",
    uiLocation: "Add Slide action",
    gapType: "no_handler",
    currentBehavior: "Add Slide button has no click handler.",
    file: "/Users/thunderstruck/Code Playground/vestledger-platform/apps/vestledger-ui/src/components/dealflow/dealflow-review.tsx",
    line: 547,
    status: 'guarded_todo_api',
  },
  'ui-api-031': {
    id: 'ui-api-031',
    route: "/dealflow-review",
    uiLocation: "Company scoring data service",
    gapType: "mock_always",
    currentBehavior: "Non-mock branch still returns mock company scoring data.",
    file: "/Users/thunderstruck/Code Playground/vestledger-platform/apps/vestledger-ui/src/services/dealflow/companyScoringService.ts",
    line: 9,
    status: 'guarded_todo_api',
  },
  'ui-api-032': {
    id: 'ui-api-032',
    route: "/dealflow-review",
    uiLocation: "Company scoring submit",
    gapType: "no_handler",
    currentBehavior: "Submit Score button has no handler.",
    file: "/Users/thunderstruck/Code Playground/vestledger-platform/apps/vestledger-ui/src/components/dealflow/company-scoring.tsx",
    line: 325,
    status: 'guarded_todo_api',
  },
  'ui-api-033': {
    id: 'ui-api-033',
    route: "/dealflow-review",
    uiLocation: "Startup application submit",
    gapType: "simulated",
    currentBehavior: "Submission uses a component-local timer and UI state patch, no API call.",
    file: "/Users/thunderstruck/Code Playground/vestledger-platform/apps/vestledger-ui/src/components/dealflow/startup-application-form.tsx",
    line: 89,
    status: 'guarded_todo_api',
  },
  'ui-api-034': {
    id: 'ui-api-034',
    route: "/ai-tools",
    uiLocation: "DD assistant target deal",
    gapType: "hardcoded",
    currentBehavior: "DD assistant is instantiated with fixed deal name Quantum AI.",
    file: "/Users/thunderstruck/Code Playground/vestledger-platform/apps/vestledger-ui/src/components/ai/ai-tools.tsx",
    line: 50,
    status: 'guarded_todo_api',
  },
  'ui-api-035': {
    id: 'ui-api-035',
    route: "/ai-tools",
    uiLocation: "DD chat initial conversation",
    gapType: "empty_state",
    currentBehavior: "Service returns mock conversation only in demo mode; API mode returns an empty conversation.",
    file: "/Users/thunderstruck/Code Playground/vestledger-platform/apps/vestledger-ui/src/services/ai/ddChatService.ts",
    line: 22,
    status: 'guarded_todo_api',
  },
  'ui-api-036': {
    id: 'ui-api-036',
    route: "/ai-tools",
    uiLocation: "DD chat response generation",
    gapType: "degraded_state",
    currentBehavior: "Service returns mock responses only in demo mode; API mode returns an explicit unavailable assistant message.",
    file: "/Users/thunderstruck/Code Playground/vestledger-platform/apps/vestledger-ui/src/services/ai/ddChatService.ts",
    line: 30,
    status: 'guarded_todo_api',
  },
  'ui-api-037': {
    id: 'ui-api-037',
    route: "/ai-tools",
    uiLocation: "DD chat send flow",
    gapType: "simulated",
    currentBehavior: "Component appends AI response after delay without backend request.",
    file: "/Users/thunderstruck/Code Playground/vestledger-platform/apps/vestledger-ui/src/components/ai/dd-chat-assistant.tsx",
    line: 76,
    status: 'guarded_todo_api',
  },
  'ui-api-038': {
    id: 'ui-api-038',
    route: "/ai-tools",
    uiLocation: "DD related document preview",
    gapType: "empty_state",
    currentBehavior: "Related document preview uses mock PDFs only in demo mode; API mode opens an unavailable-preview shell.",
    file: "/Users/thunderstruck/Code Playground/vestledger-platform/apps/vestledger-ui/src/components/ai/dd-chat-assistant.tsx",
    line: 145,
    status: 'guarded_todo_api',
  },
  'ui-api-039': {
    id: 'ui-api-039',
    route: "/ai-tools",
    uiLocation: "Pitch deck analyses service",
    gapType: "empty_state",
    currentBehavior: "Service returns mock analyses only in demo mode; API mode returns an empty analysis list.",
    file: "/Users/thunderstruck/Code Playground/vestledger-platform/apps/vestledger-ui/src/services/ai/pitchDeckService.ts",
    line: 18,
    status: 'guarded_todo_api',
  },
  'ui-api-040': {
    id: 'ui-api-040',
    route: "/ai-tools",
    uiLocation: "Pitch deck upload flow",
    gapType: "simulated",
    currentBehavior: "Upload action runs a component-local delay and local flag updates only.",
    file: "/Users/thunderstruck/Code Playground/vestledger-platform/apps/vestledger-ui/src/components/ai/pitch-deck-reader.tsx",
    line: 47,
    status: 'guarded_todo_api',
  },
  'ui-api-041': {
    id: 'ui-api-041',
    route: "/ai-tools",
    uiLocation: "Pitch deck preview URL",
    gapType: "empty_state",
    currentBehavior: "View Deck uses mock PDFs only in demo mode; API mode opens an unavailable-preview shell.",
    file: "/Users/thunderstruck/Code Playground/vestledger-platform/apps/vestledger-ui/src/components/ai/pitch-deck-reader.tsx",
    line: 107,
    status: 'guarded_todo_api',
  },
  'ui-api-042': {
    id: 'ui-api-042',
    route: "/ai-tools",
    uiLocation: "Pitch deck export action",
    gapType: "no_handler",
    currentBehavior: "Export Analysis button has no handler.",
    file: "/Users/thunderstruck/Code Playground/vestledger-platform/apps/vestledger-ui/src/components/ai/pitch-deck-reader.tsx",
    line: 119,
    status: 'guarded_todo_api',
  },
  'ui-api-043': {
    id: 'ui-api-043',
    route: "/ai-tools",
    uiLocation: "Decision writer seed data",
    gapType: "empty_state",
    currentBehavior: "Deal seed info is demo-only; API mode returns an empty deal form.",
    file: "/Users/thunderstruck/Code Playground/vestledger-platform/apps/vestledger-ui/src/services/ai/decisionWriterService.ts",
    line: 15,
    status: 'guarded_todo_api',
  },
  'ui-api-044': {
    id: 'ui-api-044',
    route: "/ai-tools",
    uiLocation: "Decision writer reasons",
    gapType: "config_owned",
    currentBehavior: "Rejection reasons are sourced from shared UI config for both demo and API modes.",
    file: "/Users/thunderstruck/Code Playground/vestledger-platform/apps/vestledger-ui/src/services/ai/decisionWriterService.ts",
    line: 20,
    status: 'guarded_todo_api',
  },
  'ui-api-045': {
    id: 'ui-api-045',
    route: "/ai-tools",
    uiLocation: "Decision writer tones",
    gapType: "config_owned",
    currentBehavior: "Tone options are sourced from shared UI config for both demo and API modes.",
    file: "/Users/thunderstruck/Code Playground/vestledger-platform/apps/vestledger-ui/src/services/ai/decisionWriterService.ts",
    line: 25,
    status: 'guarded_todo_api',
  },
  'ui-api-046': {
    id: 'ui-api-046',
    route: "/ai-tools",
    uiLocation: "Decision letter generation",
    gapType: "degraded_state",
    currentBehavior: "Mock generation runs only in demo mode; API mode returns an explicit unavailable message until backend generation is implemented.",
    file: "/Users/thunderstruck/Code Playground/vestledger-platform/apps/vestledger-ui/src/services/ai/decisionWriterService.ts",
    line: 36,
    status: 'guarded_todo_api',
  },
  'ui-api-047': {
    id: 'ui-api-047',
    route: "/ai-tools",
    uiLocation: "Decision writer generation lifecycle",
    gapType: "simulated",
    currentBehavior: "Letter generation is delayed in the component with local state patches.",
    file: "/Users/thunderstruck/Code Playground/vestledger-platform/apps/vestledger-ui/src/components/ai/decision-writer.tsx",
    line: 88,
    status: 'guarded_todo_api',
  },
  'ui-api-048': {
    id: 'ui-api-048',
    route: "/ai-tools",
    uiLocation: "Decision writer Edit button",
    gapType: "no_handler",
    currentBehavior: "Edit button has no handler.",
    file: "/Users/thunderstruck/Code Playground/vestledger-platform/apps/vestledger-ui/src/components/ai/decision-writer.tsx",
    line: 279,
    status: 'guarded_todo_api',
  },
  'ui-api-049': {
    id: 'ui-api-049',
    route: "/ai-tools",
    uiLocation: "Decision writer Export button",
    gapType: "no_handler",
    currentBehavior: "Export button has no handler.",
    file: "/Users/thunderstruck/Code Playground/vestledger-platform/apps/vestledger-ui/src/components/ai/decision-writer.tsx",
    line: 294,
    status: 'guarded_todo_api',
  },
  'ui-api-050': {
    id: 'ui-api-050',
    route: "/ai-tools",
    uiLocation: "Decision writer Send Email button",
    gapType: "no_handler",
    currentBehavior: "Send Email button has no handler.",
    file: "/Users/thunderstruck/Code Playground/vestledger-platform/apps/vestledger-ui/src/components/ai/decision-writer.tsx",
    line: 315,
    status: 'guarded_todo_api',
  },
  'ui-api-051': {
    id: 'ui-api-051',
    route: "/ai-tools",
    uiLocation: "Decision writer Save as Draft button",
    gapType: "no_handler",
    currentBehavior: "Save as Draft button has no handler.",
    file: "/Users/thunderstruck/Code Playground/vestledger-platform/apps/vestledger-ui/src/components/ai/decision-writer.tsx",
    line: 320,
    status: 'guarded_todo_api',
  },
  'ui-api-052': {
    id: 'ui-api-052',
    route: "/pipeline",
    uiLocation: "Filter action button",
    gapType: "no_handler",
    currentBehavior: "Filter button renders with no filter action wiring.",
    file: "/Users/thunderstruck/Code Playground/vestledger-platform/apps/vestledger-ui/src/components/pipeline.tsx",
    line: 300,
    status: 'guarded_todo_api',
  },
  'ui-api-053': {
    id: 'ui-api-053',
    route: "/pipeline",
    uiLocation: "Copilot suggestions error path",
    gapType: "silent_fallback",
    currentBehavior: "Suggestions request errors are swallowed to empty array.",
    file: "/Users/thunderstruck/Code Playground/vestledger-platform/apps/vestledger-ui/src/services/pipelineService.ts",
    line: 84,
    status: 'guarded_todo_api',
  },
  'ui-api-054': {
    id: 'ui-api-054',
    route: "/pipeline",
    uiLocation: "Pipeline deals payload validation",
    gapType: "fallback",
    currentBehavior: "Empty or malformed API payload falls back to empty deals list.",
    file: "/Users/thunderstruck/Code Playground/vestledger-platform/apps/vestledger-ui/src/services/shared/pipelineGateway.ts",
    line: 136,
    status: 'guarded_todo_api',
  },
  'ui-api-055': {
    id: 'ui-api-055',
    route: "/reports",
    uiLocation: "Header Report Settings action",
    gapType: "no_handler",
    currentBehavior: "Secondary action is explicit no-op function.",
    file: "/Users/thunderstruck/Code Playground/vestledger-platform/apps/vestledger-ui/src/components/reports/report-export.tsx",
    line: 92,
    status: 'guarded_todo_api',
  },
  'ui-api-056': {
    id: 'ui-api-056',
    route: "/reports",
    uiLocation: "Recent export download action",
    gapType: "no_handler",
    currentBehavior: "Completed-job Download button has no click handler.",
    file: "/Users/thunderstruck/Code Playground/vestledger-platform/apps/vestledger-ui/src/components/reports/report-export.tsx",
    line: 172,
    status: 'guarded_todo_api',
  },
  'ui-api-057': {
    id: 'ui-api-057',
    route: "/reports",
    uiLocation: "Generate and Email action",
    gapType: "no_handler",
    currentBehavior: "Generate & Email button has no handler.",
    file: "/Users/thunderstruck/Code Playground/vestledger-platform/apps/vestledger-ui/src/components/reports/report-export.tsx",
    line: 320,
    status: 'guarded_todo_api',
  },
  'ui-api-058': {
    id: 'ui-api-058',
    route: "/reports",
    uiLocation: "Export worker progress",
    gapType: "simulated",
    currentBehavior: "Export progress is time-simulated in the component rather than backend job polling.",
    file: "/Users/thunderstruck/Code Playground/vestledger-platform/apps/vestledger-ui/src/components/reports/report-export.tsx",
    line: 83,
    status: 'guarded_todo_api',
  },
  'ui-api-059': {
    id: 'ui-api-059',
    route: "/reports",
    uiLocation: "Export job completion URL",
    gapType: "empty_state",
    currentBehavior: "Completed export jobs remain without a download URL until backend export delivery is implemented.",
    file: "/Users/thunderstruck/Code Playground/vestledger-platform/apps/vestledger-ui/src/components/reports/report-export.tsx",
    line: 104,
    status: 'guarded_todo_api',
  },
  'ui-api-060': {
    id: 'ui-api-060',
    route: "/reports",
    uiLocation: "Templates and job list",
    gapType: "empty_state",
    currentBehavior: "Templates and export jobs use mock seeds only in demo mode; API mode resolves to API data or empty arrays.",
    file: "/Users/thunderstruck/Code Playground/vestledger-platform/apps/vestledger-ui/src/services/reports/reportExportService.ts",
    line: 21,
    status: 'guarded_todo_api',
  },
  'ui-api-061': {
    id: 'ui-api-061',
    route: "/integrations",
    uiLocation: "Integration Configure action",
    gapType: "toast_only",
    currentBehavior: "Configure button only shows a toast.",
    file: "/Users/thunderstruck/Code Playground/vestledger-platform/apps/vestledger-ui/src/components/integrations/index.tsx",
    line: 149,
    status: 'guarded_todo_api',
  },
  'ui-api-062': {
    id: 'ui-api-062',
    route: "/integrations",
    uiLocation: "Snapshot hydration",
    gapType: "empty_state",
    currentBehavior: "If API arrays are empty, snapshot resolves to API-derived empty state; mock seeds are demo-only.",
    file: "/Users/thunderstruck/Code Playground/vestledger-platform/apps/vestledger-ui/src/services/integrationsService.ts",
    line: 359,
    status: 'guarded_todo_api',
  },
  'ui-api-063': {
    id: 'ui-api-063',
    route: "/integrations",
    uiLocation: "Calendar connect/disconnect/sync/update",
    gapType: "local_only",
    currentBehavior: "Calendar mutations are applied in local snapshot store.",
    file: "/Users/thunderstruck/Code Playground/vestledger-platform/apps/vestledger-ui/src/services/integrationsService.ts",
    line: 401,
    status: 'guarded_todo_api',
  },
  'ui-api-064': {
    id: 'ui-api-064',
    route: "/integrations",
    uiLocation: "Configure calendar rules",
    gapType: "no_op",
    currentBehavior: "Rules configuration is explicitly a no-op placeholder.",
    file: "/Users/thunderstruck/Code Playground/vestledger-platform/apps/vestledger-ui/src/services/integrationsService.ts",
    line: 467,
    status: 'guarded_todo_api',
  },
  'ui-api-065': {
    id: 'ui-api-065',
    route: "/collaboration",
    uiLocation: "Add message",
    gapType: "local_only",
    currentBehavior: "Message is appended to local collaboration cache only.",
    file: "/Users/thunderstruck/Code Playground/vestledger-platform/apps/vestledger-ui/src/services/collaboration/collaborationService.ts",
    line: 197,
    status: 'guarded_todo_api',
  },
  'ui-api-066': {
    id: 'ui-api-066',
    route: "/collaboration",
    uiLocation: "Create task",
    gapType: "local_only",
    currentBehavior: "Task is inserted into local collaboration cache only.",
    file: "/Users/thunderstruck/Code Playground/vestledger-platform/apps/vestledger-ui/src/services/collaboration/collaborationService.ts",
    line: 226,
    status: 'guarded_todo_api',
  },
  'ui-api-067': {
    id: 'ui-api-067',
    route: "/collaboration",
    uiLocation: "Update task status",
    gapType: "local_only",
    currentBehavior: "Task status changes mutate local cache only.",
    file: "/Users/thunderstruck/Code Playground/vestledger-platform/apps/vestledger-ui/src/services/collaboration/collaborationService.ts",
    line: 247,
    status: 'guarded_todo_api',
  },
  'ui-api-068': {
    id: 'ui-api-068',
    route: "/home",
    uiLocation: "Dashboard initial hydration",
    gapType: "mock_seed",
    currentBehavior: "Hook initializes dashboard from mock data before async fetch.",
    file: "/Users/thunderstruck/Code Playground/vestledger-platform/apps/vestledger-ui/src/hooks/use-dashboard-data.ts",
    line: 19,
    status: 'guarded_todo_api',
  },
  'ui-api-069': {
    id: 'ui-api-069',
    route: "/home",
    uiLocation: "Dashboard API empty/malformed/error path",
    gapType: "mock_fallback",
    currentBehavior: "Service falls back to mock dashboard payload.",
    file: "/Users/thunderstruck/Code Playground/vestledger-platform/apps/vestledger-ui/src/services/dashboard/dashboardDataService.ts",
    line: 22,
    status: 'guarded_todo_api',
  },
  'ui-api-070': {
    id: 'ui-api-070',
    route: "/home",
    uiLocation: "Fund metric change values",
    gapType: "hardcoded",
    currentBehavior: "Metric deltas are static constants rather than API-backed.",
    file: "/Users/thunderstruck/Code Playground/vestledger-platform/apps/vestledger-ui/src/components/dashboard-v2.tsx",
    line: 32,
    status: 'guarded_todo_api',
  },
  'ui-api-071': {
    id: 'ui-api-071',
    route: "/home",
    uiLocation: "Analyst dashboard primary action",
    gapType: "no_handler",
    currentBehavior: "New Deal Sourcing button has no handler.",
    file: "/Users/thunderstruck/Code Playground/vestledger-platform/apps/vestledger-ui/src/components/dashboards/analyst-dashboard.tsx",
    line: 41,
    status: 'guarded_todo_api',
  },
  'ui-api-072': {
    id: 'ui-api-072',
    route: "/home",
    uiLocation: "Analyst dashboard section action",
    gapType: "no_handler",
    currentBehavior: "View All button has no handler.",
    file: "/Users/thunderstruck/Code Playground/vestledger-platform/apps/vestledger-ui/src/components/dashboards/analyst-dashboard.tsx",
    line: 51,
    status: 'guarded_todo_api',
  },
  'ui-api-073': {
    id: 'ui-api-073',
    route: "/home",
    uiLocation: "Ops dashboard actions",
    gapType: "no_handler",
    currentBehavior: "Export Reports and New Capital Call buttons have no handlers.",
    file: "/Users/thunderstruck/Code Playground/vestledger-platform/apps/vestledger-ui/src/components/dashboards/ops-dashboard.tsx",
    line: 42,
    status: 'guarded_todo_api',
  },
  'ui-api-074': {
    id: 'ui-api-074',
    route: "/home",
    uiLocation: "IR dashboard actions",
    gapType: "no_handler",
    currentBehavior: "Draft Update and Schedule Call buttons have no handlers.",
    file: "/Users/thunderstruck/Code Playground/vestledger-platform/apps/vestledger-ui/src/components/dashboards/ir-dashboard.tsx",
    line: 42,
    status: 'guarded_todo_api',
  },
  'ui-api-075': {
    id: 'ui-api-075',
    route: "/home",
    uiLocation: "IR dashboard section action",
    gapType: "no_handler",
    currentBehavior: "View All button has no handler.",
    file: "/Users/thunderstruck/Code Playground/vestledger-platform/apps/vestledger-ui/src/components/dashboards/ir-dashboard.tsx",
    line: 56,
    status: 'guarded_todo_api',
  },
  'ui-api-076': {
    id: 'ui-api-076',
    route: "/home",
    uiLocation: "Auditor dashboard actions",
    gapType: "no_handler",
    currentBehavior: "Search Records and Export Audit Log buttons have no handlers.",
    file: "/Users/thunderstruck/Code Playground/vestledger-platform/apps/vestledger-ui/src/components/dashboards/auditor-dashboard.tsx",
    line: 42,
    status: 'guarded_todo_api',
  },
  'ui-api-077': {
    id: 'ui-api-077',
    route: "/home",
    uiLocation: "Auditor dashboard section action",
    gapType: "no_handler",
    currentBehavior: "View Full Log button has no handler.",
    file: "/Users/thunderstruck/Code Playground/vestledger-platform/apps/vestledger-ui/src/components/dashboards/auditor-dashboard.tsx",
    line: 56,
    status: 'guarded_todo_api',
  },
  'ui-api-078': {
    id: 'ui-api-078',
    route: "/home",
    uiLocation: "Researcher dashboard actions",
    gapType: "no_handler",
    currentBehavior: "Query Data and New Report buttons have no handlers.",
    file: "/Users/thunderstruck/Code Playground/vestledger-platform/apps/vestledger-ui/src/components/dashboards/researcher-dashboard.tsx",
    line: 42,
    status: 'guarded_todo_api',
  },
  'ui-api-079': {
    id: 'ui-api-079',
    route: "/home",
    uiLocation: "Researcher report download action",
    gapType: "no_handler",
    currentBehavior: "Per-report download icon button has no handler.",
    file: "/Users/thunderstruck/Code Playground/vestledger-platform/apps/vestledger-ui/src/components/dashboards/researcher-dashboard.tsx",
    line: 77,
    status: 'guarded_todo_api',
  },
  'ui-api-080': {
    id: 'ui-api-080',
    route: "/home",
    uiLocation: "LP dashboard top actions",
    gapType: "no_handler",
    currentBehavior: "Schedule Meeting and Download Statements buttons have no handlers.",
    file: "/Users/thunderstruck/Code Playground/vestledger-platform/apps/vestledger-ui/src/components/dashboards/lp-dashboard.tsx",
    line: 57,
    status: 'guarded_todo_api',
  },
  'ui-api-081': {
    id: 'ui-api-081',
    route: "/home",
    uiLocation: "LP pending call pay action",
    gapType: "no_handler",
    currentBehavior: "Pay Now button has no handler.",
    file: "/Users/thunderstruck/Code Playground/vestledger-platform/apps/vestledger-ui/src/components/dashboards/lp-dashboard.tsx",
    line: 163,
    status: 'guarded_todo_api',
  },
  'ui-api-082': {
    id: 'ui-api-082',
    route: "/home",
    uiLocation: "LP signature action",
    gapType: "no_handler",
    currentBehavior: "Sign Document button has no handler.",
    file: "/Users/thunderstruck/Code Playground/vestledger-platform/apps/vestledger-ui/src/components/dashboards/lp-dashboard.tsx",
    line: 216,
    status: 'guarded_todo_api',
  },
  'ui-api-083': {
    id: 'ui-api-083',
    route: "/home",
    uiLocation: "LP document download action",
    gapType: "no_handler",
    currentBehavior: "Recent document download icon button has no handler.",
    file: "/Users/thunderstruck/Code Playground/vestledger-platform/apps/vestledger-ui/src/components/dashboards/lp-dashboard.tsx",
    line: 254,
    status: 'guarded_todo_api',
  },
  'ui-api-084': {
    id: 'ui-api-084',
    route: "/home",
    uiLocation: "Ops snapshot compliance alerts",
    gapType: "partial_api",
    currentBehavior: "Uses mock compliance alerts because API does not provide this section fully.",
    file: "/Users/thunderstruck/Code Playground/vestledger-platform/apps/vestledger-ui/src/services/dashboards/opsDashboardService.ts",
    line: 37,
    status: 'wired_to_existing_api',
  },
  'ui-api-085': {
    id: 'ui-api-085',
    route: "/home",
    uiLocation: "IR recent interactions",
    gapType: "partial_api",
    currentBehavior: "Uses mock recent interactions because API does not provide section fully.",
    file: "/Users/thunderstruck/Code Playground/vestledger-platform/apps/vestledger-ui/src/services/dashboards/irDashboardService.ts",
    line: 36,
    status: 'wired_to_existing_api',
  },
  'ui-api-086': {
    id: 'ui-api-086',
    route: "/home",
    uiLocation: "Auditor non-metric sections",
    gapType: "partial_api",
    currentBehavior: "Audit trail and compliance items are mock fallback; some metrics are placeholders.",
    file: "/Users/thunderstruck/Code Playground/vestledger-platform/apps/vestledger-ui/src/services/dashboards/auditorDashboardService.ts",
    line: 29,
    status: 'wired_to_existing_api',
  },
  'ui-api-087': {
    id: 'ui-api-087',
    route: "/home",
    uiLocation: "Researcher reports generated metric",
    gapType: "hardcoded",
    currentBehavior: "Reports generated metric is hardcoded fallback value.",
    file: "/Users/thunderstruck/Code Playground/vestledger-platform/apps/vestledger-ui/src/services/dashboards/researcherDashboardService.ts",
    line: 35,
    status: 'guarded_todo_api',
  },
  'ui-api-088': {
    id: 'ui-api-088',
    route: "/home",
    uiLocation: "LP dashboard missing lpId path",
    gapType: "fallback",
    currentBehavior: "Without lpId, service falls back to default snapshot.",
    file: "/Users/thunderstruck/Code Playground/vestledger-platform/apps/vestledger-ui/src/services/dashboards/lpDashboardService.ts",
    line: 233,
    status: 'guarded_todo_api',
  },
  'ui-api-089': {
    id: 'ui-api-089',
    route: "/settings",
    uiLocation: "Profile Save/Cancel",
    gapType: "no_handler",
    currentBehavior: "Save Changes and Cancel buttons have no data persistence wiring.",
    file: "/Users/thunderstruck/Code Playground/vestledger-platform/apps/vestledger-ui/src/components/settings.tsx",
    line: 386,
    status: 'guarded_todo_api',
  },
  'ui-api-090': {
    id: 'ui-api-090',
    route: "/settings",
    uiLocation: "Notification Save Preferences",
    gapType: "no_handler",
    currentBehavior: "Save Preferences button has no persistence handler.",
    file: "/Users/thunderstruck/Code Playground/vestledger-platform/apps/vestledger-ui/src/components/settings.tsx",
    line: 435,
    status: 'guarded_todo_api',
  },
  'ui-api-091': {
    id: 'ui-api-091',
    route: "/settings",
    uiLocation: "2FA toggle",
    gapType: "local_only",
    currentBehavior: "Enable/Disable 2FA toggles local UI state only.",
    file: "/Users/thunderstruck/Code Playground/vestledger-platform/apps/vestledger-ui/src/components/settings.tsx",
    line: 489,
    status: 'guarded_todo_api',
  },
  'ui-api-092': {
    id: 'ui-api-092',
    route: "/settings",
    uiLocation: "Session revoke",
    gapType: "no_handler",
    currentBehavior: "Revoke session button has no handler.",
    file: "/Users/thunderstruck/Code Playground/vestledger-platform/apps/vestledger-ui/src/components/settings.tsx",
    line: 514,
    status: 'guarded_todo_api',
  },
  'ui-api-093': {
    id: 'ui-api-093',
    route: "/settings",
    uiLocation: "Update password",
    gapType: "no_handler",
    currentBehavior: "Update Password button has no backend handler.",
    file: "/Users/thunderstruck/Code Playground/vestledger-platform/apps/vestledger-ui/src/components/settings.tsx",
    line: 522,
    status: 'guarded_todo_api',
  },
  'ui-api-094': {
    id: 'ui-api-094',
    route: "/settings",
    uiLocation: "Change plan",
    gapType: "no_handler",
    currentBehavior: "Change Plan button has no handler.",
    file: "/Users/thunderstruck/Code Playground/vestledger-platform/apps/vestledger-ui/src/components/settings.tsx",
    line: 641,
    status: 'guarded_todo_api',
  },
  'ui-api-095': {
    id: 'ui-api-095',
    route: "/settings",
    uiLocation: "Payment method edit/remove",
    gapType: "no_handler",
    currentBehavior: "Edit and Remove payment method buttons have no handlers.",
    file: "/Users/thunderstruck/Code Playground/vestledger-platform/apps/vestledger-ui/src/components/settings.tsx",
    line: 660,
    status: 'guarded_todo_api',
  },
  'ui-api-096': {
    id: 'ui-api-096',
    route: "/settings",
    uiLocation: "Add payment method",
    gapType: "no_handler",
    currentBehavior: "Add Payment Method button has no handler.",
    file: "/Users/thunderstruck/Code Playground/vestledger-platform/apps/vestledger-ui/src/components/settings.tsx",
    line: 665,
    status: 'guarded_todo_api',
  },
  'ui-api-097': {
    id: 'ui-api-097',
    route: "/settings",
    uiLocation: "Billing history download",
    gapType: "no_handler",
    currentBehavior: "Invoice Download buttons have no handlers.",
    file: "/Users/thunderstruck/Code Playground/vestledger-platform/apps/vestledger-ui/src/components/settings.tsx",
    line: 686,
    status: 'guarded_todo_api',
  },
  'ui-api-098': {
    id: 'ui-api-098',
    route: "/settings",
    uiLocation: "Team access backend",
    gapType: "mock_backend",
    currentBehavior: "Team access service reads/mutates mock superadmin state, not platform API.",
    file: "/Users/thunderstruck/Code Playground/vestledger-platform/apps/vestledger-ui/src/services/internal/teamAccessService.ts",
    line: 2,
    status: 'guarded_todo_api',
  },
  'ui-api-099': {
    id: 'ui-api-099',
    route: "/contacts",
    uiLocation: "Contact quick actions",
    gapType: "no_handler",
    currentBehavior: "Send Email, Call, Schedule Meeting, Add Note buttons have no handlers.",
    file: "/Users/thunderstruck/Code Playground/vestledger-platform/apps/vestledger-ui/src/components/crm/contacts.tsx",
    line: 609,
    status: 'guarded_todo_api',
  },
  'ui-api-100': {
    id: 'ui-api-100',
    route: "/contacts",
    uiLocation: "Interaction update",
    gapType: "local_only",
    currentBehavior: "Update interaction mutates local cached timeline only.",
    file: "/Users/thunderstruck/Code Playground/vestledger-platform/apps/vestledger-ui/src/services/crm/contactsService.ts",
    line: 608,
    status: 'guarded_todo_api',
  },
  'ui-api-101': {
    id: 'ui-api-101',
    route: "/contacts",
    uiLocation: "Interaction delete",
    gapType: "local_only",
    currentBehavior: "Delete interaction mutates local cached arrays only.",
    file: "/Users/thunderstruck/Code Playground/vestledger-platform/apps/vestledger-ui/src/services/crm/contactsService.ts",
    line: 619,
    status: 'guarded_todo_api',
  },
  'ui-api-102': {
    id: 'ui-api-102',
    route: "/contacts",
    uiLocation: "Interaction link to deal",
    gapType: "local_only",
    currentBehavior: "Linking interaction to deal mutates local cache only.",
    file: "/Users/thunderstruck/Code Playground/vestledger-platform/apps/vestledger-ui/src/services/crm/contactsService.ts",
    line: 629,
    status: 'guarded_todo_api',
  },
  'ui-api-103': {
    id: 'ui-api-103',
    route: "/contacts",
    uiLocation: "Email auto-capture toggle",
    gapType: "local_only",
    currentBehavior: "Auto-capture toggle mutates local email account cache only.",
    file: "/Users/thunderstruck/Code Playground/vestledger-platform/apps/vestledger-ui/src/services/crm/contactsService.ts",
    line: 718,
    status: 'guarded_todo_api',
  },
  'ui-api-104': {
    id: 'ui-api-104',
    route: "/contacts",
    uiLocation: "CRM read fallbacks",
    gapType: "empty_state",
    currentBehavior: "Read functions fall back to cached CRM snapshots or empty state on API issues; mock seeds are demo-only.",
    file: "/Users/thunderstruck/Code Playground/vestledger-platform/apps/vestledger-ui/src/services/crm/contactsService.ts",
    line: 405,
    status: 'guarded_todo_api',
  },
  'ui-api-105': {
    id: 'ui-api-105',
    route: "/deal-intelligence",
    uiLocation: "Top Upload Document action",
    gapType: "no_handler",
    currentBehavior: "Header Upload Document button has no handler.",
    file: "/Users/thunderstruck/Code Playground/vestledger-platform/apps/vestledger-ui/src/components/deal-intelligence.tsx",
    line: 297,
    status: 'guarded_todo_api',
  },
  'ui-api-106': {
    id: 'ui-api-106',
    route: "/deal-intelligence",
    uiLocation: "Document Library Export/Upload actions",
    gapType: "no_handler",
    currentBehavior: "Library Export and Upload buttons have no handlers.",
    file: "/Users/thunderstruck/Code Playground/vestledger-platform/apps/vestledger-ui/src/components/deal-intelligence.tsx",
    line: 781,
    status: 'guarded_todo_api',
  },
  'ui-api-107': {
    id: 'ui-api-107',
    route: "/deal-intelligence",
    uiLocation: "Document preview icon",
    gapType: "no_handler",
    currentBehavior: "Per-document preview icon button has no handler.",
    file: "/Users/thunderstruck/Code Playground/vestledger-platform/apps/vestledger-ui/src/components/deal-intelligence.tsx",
    line: 838,
    status: 'guarded_todo_api',
  },
  'ui-api-108': {
    id: 'ui-api-108',
    route: "/deal-intelligence",
    uiLocation: "Document download icon",
    gapType: "no_handler",
    currentBehavior: "Per-document download icon button has no handler.",
    file: "/Users/thunderstruck/Code Playground/vestledger-platform/apps/vestledger-ui/src/components/deal-intelligence.tsx",
    line: 847,
    status: 'guarded_todo_api',
  },
  'ui-api-109': {
    id: 'ui-api-109',
    route: "/deal-intelligence",
    uiLocation: "Analysis tab",
    gapType: "placeholder",
    currentBehavior: "Analysis workspace is staged placeholder for future release.",
    file: "/Users/thunderstruck/Code Playground/vestledger-platform/apps/vestledger-ui/src/components/deal-intelligence.tsx",
    line: 867,
    status: 'guarded_todo_api',
  },
  'ui-api-110': {
    id: 'ui-api-110',
    route: "/deal-intelligence",
    uiLocation: "IC materials tab",
    gapType: "placeholder",
    currentBehavior: "IC materials workspace is staged placeholder for future release.",
    file: "/Users/thunderstruck/Code Playground/vestledger-platform/apps/vestledger-ui/src/components/deal-intelligence.tsx",
    line: 876,
    status: 'guarded_todo_api',
  },
  'ui-api-111': {
    id: 'ui-api-111',
    route: "/deal-intelligence",
    uiLocation: "Document API failure path",
    gapType: "degraded_fallback",
    currentBehavior: "If documents fetch fails, service returns empty docs and renders without backend docs.",
    file: "/Users/thunderstruck/Code Playground/vestledger-platform/apps/vestledger-ui/src/services/dealIntelligence/dealIntelligenceService.ts",
    line: 334,
    status: 'guarded_todo_api',
  },
  'ui-api-112': {
    id: 'ui-api-112',
    route: "/portfolio",
    uiLocation: "Overview Filters action",
    gapType: "no_handler",
    currentBehavior: "Filters button has no handler.",
    file: "/Users/thunderstruck/Code Playground/vestledger-platform/apps/vestledger-ui/src/components/portfolio-dashboard.tsx",
    line: 246,
    status: 'guarded_todo_api',
  },
  'ui-api-113': {
    id: 'ui-api-113',
    route: "/portfolio",
    uiLocation: "Overview Export Report action",
    gapType: "no_handler",
    currentBehavior: "Export Report button has no handler.",
    file: "/Users/thunderstruck/Code Playground/vestledger-platform/apps/vestledger-ui/src/components/portfolio-dashboard.tsx",
    line: 254,
    status: 'guarded_todo_api',
  },
  'ui-api-114': {
    id: 'ui-api-114',
    route: "/portfolio",
    uiLocation: "Documents top Upload action",
    gapType: "no_handler",
    currentBehavior: "Upload Document button has no handler.",
    file: "/Users/thunderstruck/Code Playground/vestledger-platform/apps/vestledger-ui/src/components/portfolio-documents.tsx",
    line: 48,
    status: 'guarded_todo_api',
  },
  'ui-api-115': {
    id: 'ui-api-115',
    route: "/portfolio",
    uiLocation: "Documents list Export action",
    gapType: "no_handler",
    currentBehavior: "Export button has no handler.",
    file: "/Users/thunderstruck/Code Playground/vestledger-platform/apps/vestledger-ui/src/components/portfolio-documents.tsx",
    line: 192,
    status: 'guarded_todo_api',
  },
  'ui-api-116': {
    id: 'ui-api-116',
    route: "/portfolio",
    uiLocation: "Documents preview URL",
    gapType: "mock_fallback",
    currentBehavior: "Preview action opens mock document URL.",
    file: "/Users/thunderstruck/Code Playground/vestledger-platform/apps/vestledger-ui/src/components/portfolio-documents.tsx",
    line: 255,
    status: 'guarded_todo_api',
  },
  'ui-api-117': {
    id: 'ui-api-117',
    route: "/portfolio",
    uiLocation: "Documents download icon",
    gapType: "no_handler",
    currentBehavior: "Per-document download icon has no handler.",
    file: "/Users/thunderstruck/Code Playground/vestledger-platform/apps/vestledger-ui/src/components/portfolio-documents.tsx",
    line: 265,
    status: 'guarded_todo_api',
  },
  'ui-api-118': {
    id: 'ui-api-118',
    route: "/portfolio",
    uiLocation: "Documents awaiting-upload icon",
    gapType: "no_handler",
    currentBehavior: "Per-document upload icon has no handler.",
    file: "/Users/thunderstruck/Code Playground/vestledger-platform/apps/vestledger-ui/src/components/portfolio-documents.tsx",
    line: 276,
    status: 'guarded_todo_api',
  },
  'ui-api-119': {
    id: 'ui-api-119',
    route: "/portfolio",
    uiLocation: "Updates load more action",
    gapType: "no_handler",
    currentBehavior: "Load More Updates button has no handler.",
    file: "/Users/thunderstruck/Code Playground/vestledger-platform/apps/vestledger-ui/src/components/portfolio-updates.tsx",
    line: 209,
    status: 'guarded_todo_api',
  },
  'ui-api-120': {
    id: 'ui-api-120',
    route: "/portfolio",
    uiLocation: "Snapshot without fund",
    gapType: "empty_state",
    currentBehavior: "When fundId is missing service returns cached API snapshot or empty state; mock seeds are demo-only.",
    file: "/Users/thunderstruck/Code Playground/vestledger-platform/apps/vestledger-ui/src/services/portfolio/portfolioDataService.ts",
    line: 350,
    status: 'guarded_todo_api',
  },
  'ui-api-121': {
    id: 'ui-api-121',
    route: "/portfolio",
    uiLocation: "Documents snapshot without fund",
    gapType: "empty_state",
    currentBehavior: "When fundId is missing docs service returns cached API snapshot or empty state; mock seeds are demo-only.",
    file: "/Users/thunderstruck/Code Playground/vestledger-platform/apps/vestledger-ui/src/services/portfolio/portfolioDocumentsService.ts",
    line: 385,
    status: 'guarded_todo_api',
  },
  'ui-api-122': {
    id: 'ui-api-122',
    route: "/portfolio",
    uiLocation: "Page metrics source",
    gapType: "mock_fallback",
    currentBehavior: "Page metrics service proxies to mock metrics in mock mode and fallback snapshots otherwise.",
    file: "/Users/thunderstruck/Code Playground/vestledger-platform/apps/vestledger-ui/src/services/portfolio/portfolioPageMetricsService.ts",
    line: 12,
    status: 'guarded_todo_api',
  },
  'ui-api-123': {
    id: 'ui-api-123',
    route: "/notifications",
    uiLocation: "Mark as read persistence",
    gapType: "local_only",
    currentBehavior: "Mark as read mutates Redux state only; no API write.",
    file: "/Users/thunderstruck/Code Playground/vestledger-platform/apps/vestledger-ui/src/store/slices/alertsSlice.ts",
    line: 47,
    status: 'guarded_todo_api',
  },
  'ui-api-124': {
    id: 'ui-api-124',
    route: "/audit-trail",
    uiLocation: "Events read fallback",
    gapType: "empty_state",
    currentBehavior: "Events service returns cached API events or empty state on API failure; mock seeds are demo-only.",
    file: "/Users/thunderstruck/Code Playground/vestledger-platform/apps/vestledger-ui/src/services/blockchain/auditTrailService.ts",
    line: 128,
    status: 'guarded_todo_api',
  },
  'ui-api-125': {
    id: 'ui-api-125',
    route: "/compliance",
    uiLocation: "Top upload action",
    gapType: "toast_only",
    currentBehavior: "Upload Document action only displays informational toast.",
    file: "/Users/thunderstruck/Code Playground/vestledger-platform/apps/vestledger-ui/src/components/back-office/compliance.tsx",
    line: 51,
    status: 'guarded_todo_api',
  },
  'ui-api-126': {
    id: 'ui-api-126',
    route: "/compliance",
    uiLocation: "Top export action",
    gapType: "toast_only",
    currentBehavior: "Export Report action only displays success toast.",
    file: "/Users/thunderstruck/Code Playground/vestledger-platform/apps/vestledger-ui/src/components/back-office/compliance.tsx",
    line: 58,
    status: 'guarded_todo_api',
  },
  'ui-api-127': {
    id: 'ui-api-127',
    route: "/compliance",
    uiLocation: "Regulatory filing download",
    gapType: "no_handler",
    currentBehavior: "Download button in filing rows has no handler.",
    file: "/Users/thunderstruck/Code Playground/vestledger-platform/apps/vestledger-ui/src/components/back-office/compliance.tsx",
    line: 317,
    status: 'guarded_todo_api',
  },
  'ui-api-128': {
    id: 'ui-api-128',
    route: "/tax-center",
    uiLocation: "Primary tax actions",
    gapType: "toast_only",
    currentBehavior: "Generate K-1 and Upload Documents actions show toasts only.",
    file: "/Users/thunderstruck/Code Playground/vestledger-platform/apps/vestledger-ui/src/components/back-office/tax-center.tsx",
    line: 87,
    status: 'guarded_todo_api',
  },
  'ui-api-129': {
    id: 'ui-api-129',
    route: "/tax-center",
    uiLocation: "Ready-to-send actions",
    gapType: "no_handler",
    currentBehavior: "Send All K-1s and Preview Email buttons have no handlers.",
    file: "/Users/thunderstruck/Code Playground/vestledger-platform/apps/vestledger-ui/src/components/back-office/tax-center.tsx",
    line: 436,
    status: 'guarded_todo_api',
  },
  'ui-api-130': {
    id: 'ui-api-130',
    route: "/409a-valuations",
    uiLocation: "Request New Valuation action",
    gapType: "no_handler",
    currentBehavior: "Primary action has empty handler body.",
    file: "/Users/thunderstruck/Code Playground/vestledger-platform/apps/vestledger-ui/src/components/back-office/valuation-409a.tsx",
    line: 108,
    status: 'guarded_todo_api',
  },
  'ui-api-131': {
    id: 'ui-api-131',
    route: "/409a-valuations",
    uiLocation: "Download valuation report action",
    gapType: "no_handler",
    currentBehavior: "Download Report button has no handler.",
    file: "/Users/thunderstruck/Code Playground/vestledger-platform/apps/vestledger-ui/src/components/back-office/valuation-409a.tsx",
    line: 176,
    status: 'guarded_todo_api',
  },
  'ui-api-132': {
    id: 'ui-api-132',
    route: "/fund-admin",
    uiLocation: "LP responses data source",
    gapType: "mock_always",
    currentBehavior: "In API mode LP responses still return mock list.",
    file: "/Users/thunderstruck/Code Playground/vestledger-platform/apps/vestledger-ui/src/services/backOffice/fundAdminService.ts",
    line: 241,
    status: 'guarded_todo_api',
  },
  'ui-api-133': {
    id: 'ui-api-133',
    route: "/fund-admin",
    uiLocation: "Fund admin export activity",
    gapType: "local_only",
    currentBehavior: "Export activity returns generated timestamp only.",
    file: "/Users/thunderstruck/Code Playground/vestledger-platform/apps/vestledger-ui/src/services/backOffice/fundAdminService.ts",
    line: 278,
    status: 'guarded_todo_api',
  },
  'ui-api-134': {
    id: 'ui-api-134',
    route: "/fund-admin",
    uiLocation: "NAV service no-fund read",
    gapType: "degraded_path",
    currentBehavior: "In API mode without fundId NAV list returns empty array.",
    file: "/Users/thunderstruck/Code Playground/vestledger-platform/apps/vestledger-ui/src/services/backOffice/navService.ts",
    line: 75,
    status: 'guarded_todo_api',
  },
  'ui-api-135': {
    id: 'ui-api-135',
    route: "/fund-admin",
    uiLocation: "Carry service no-fund read",
    gapType: "degraded_path",
    currentBehavior: "In API mode without fundId carry terms/accruals return empty arrays.",
    file: "/Users/thunderstruck/Code Playground/vestledger-platform/apps/vestledger-ui/src/services/backOffice/carryService.ts",
    line: 83,
    status: 'guarded_todo_api',
  },
  'ui-api-136': {
    id: 'ui-api-136',
    route: "/fund-admin",
    uiLocation: "Expense service no-fund read",
    gapType: "degraded_path",
    currentBehavior: "In API mode without fundId expenses return empty array.",
    file: "/Users/thunderstruck/Code Playground/vestledger-platform/apps/vestledger-ui/src/services/backOffice/expenseService.ts",
    line: 68,
    status: 'guarded_todo_api',
  },
  'ui-api-137': {
    id: 'ui-api-137',
    route: "/fund-admin",
    uiLocation: "Secondary transfer no-fund read",
    gapType: "degraded_path",
    currentBehavior: "In API mode without fundId transfers return empty array.",
    file: "/Users/thunderstruck/Code Playground/vestledger-platform/apps/vestledger-ui/src/services/backOffice/secondaryTransferService.ts",
    line: 121,
    status: 'guarded_todo_api',
  },
  'ui-api-138': {
    id: 'ui-api-138',
    route: "/fund-admin/distributions/new",
    uiLocation: "Draft persistence note",
    gapType: "local_only",
    currentBehavior: "Wizard explicitly states drafts are local until backend wiring.",
    file: "/Users/thunderstruck/Code Playground/vestledger-platform/apps/vestledger-ui/src/components/fund-admin/distributions/distribution-wizard.tsx",
    line: 1304,
    status: 'guarded_todo_api',
  },
  'ui-api-139': {
    id: 'ui-api-139',
    route: "/fund-admin/distributions/calendar",
    uiLocation: "Scheduled distribution draft events",
    gapType: "local_only",
    currentBehavior: "New schedule entries are written to local scheduledDrafts array.",
    file: "/Users/thunderstruck/Code Playground/vestledger-platform/apps/vestledger-ui/src/components/fund-admin/distributions/distribution-calendar.tsx",
    line: 158,
    status: 'guarded_todo_api',
  },
  'ui-api-140': {
    id: 'ui-api-140',
    route: "/fund-admin/distributions/[id]",
    uiLocation: "Statements download action",
    gapType: "no_handler",
    currentBehavior: "Download PDF button has no handler.",
    file: "/Users/thunderstruck/Code Playground/vestledger-platform/apps/vestledger-ui/src/components/fund-admin/distributions/distribution-detail.tsx",
    line: 378,
    status: 'guarded_todo_api',
  },
  'ui-api-141': {
    id: 'ui-api-141',
    route: "/fund-admin/distributions/[id]",
    uiLocation: "Statement preview URL",
    gapType: "empty_state",
    currentBehavior: "Statement preview uses mock PDFs only in demo mode; API mode leaves preview unavailable until statements are generated.",
    file: "/Users/thunderstruck/Code Playground/vestledger-platform/apps/vestledger-ui/src/components/fund-admin/distributions/statement-generator.tsx",
    line: 101,
    status: 'guarded_todo_api',
  },
  'ui-api-142': {
    id: 'ui-api-142',
    route: "/fund-admin/distributions/[id]",
    uiLocation: "Generate statements action",
    gapType: "no_handler",
    currentBehavior: "Generate Statements button has no handler.",
    file: "/Users/thunderstruck/Code Playground/vestledger-platform/apps/vestledger-ui/src/components/fund-admin/distributions/statement-generator.tsx",
    line: 240,
    status: 'guarded_todo_api',
  },
  'ui-api-143': {
    id: 'ui-api-143',
    route: "/fund-admin/distributions/[id]",
    uiLocation: "Statement bulk actions",
    gapType: "no_handler",
    currentBehavior: "Request Download All, Email All, and Print All buttons have no handlers.",
    file: "/Users/thunderstruck/Code Playground/vestledger-platform/apps/vestledger-ui/src/components/fund-admin/distributions/statement-generator.tsx",
    line: 254,
    status: 'guarded_todo_api',
  },
  'ui-api-144': {
    id: 'ui-api-144',
    route: "/fund-admin/distributions/[id]",
    uiLocation: "Tax forms download actions",
    gapType: "no_handler",
    currentBehavior: "Download All Tax Forms and per-form Download buttons have no handlers.",
    file: "/Users/thunderstruck/Code Playground/vestledger-platform/apps/vestledger-ui/src/components/fund-admin/distributions/statement-generator.tsx",
    line: 274,
    status: 'guarded_todo_api',
  },
  'ui-api-145': {
    id: 'ui-api-145',
    route: "/waterfall",
    uiLocation: "Starter scenario seed",
    gapType: "mock_seed",
    currentBehavior: "Starter scenario builder seeds from mock templates and investor classes.",
    file: "/Users/thunderstruck/Code Playground/vestledger-platform/apps/vestledger-ui/src/components/waterfall/waterfall-modeling.tsx",
    line: 69,
    status: 'guarded_todo_api',
  },
  'ui-api-146': {
    id: 'ui-api-146',
    route: "/waterfall",
    uiLocation: "Export request flow",
    gapType: "ui_only",
    currentBehavior: "Export preview/request is UI-only until backend service wiring.",
    file: "/Users/thunderstruck/Code Playground/vestledger-platform/apps/vestledger-ui/src/components/waterfall/export-menu.tsx",
    line: 262,
    status: 'guarded_todo_api',
  },
  'ui-api-147': {
    id: 'ui-api-147',
    route: "/superadmin",
    uiLocation: "Tenant/user/invite management backend",
    gapType: "mock_backend",
    currentBehavior: "Superadmin service reads and mutates in-memory mock state.",
    file: "/Users/thunderstruck/Code Playground/vestledger-platform/apps/vestledger-ui/src/services/internal/superadminService.ts",
    line: 1,
    status: 'guarded_todo_api',
  },
  'ui-api-148': {
    id: 'ui-api-148',
    route: "/(public)/eoi",
    uiLocation: "EOI submit flow",
    gapType: "simulated",
    currentBehavior: "EOI form submit uses timeout simulation and local submitted state.",
    file: "/Users/thunderstruck/Code Playground/vestledger-platform/apps/vestledger-ui/app/(public)/eoi/page.tsx",
    line: 16,
    status: 'guarded_todo_api',
  },
};


export const uiApiResolutionRecords: UiApiResolutionRecord[] = Object.values(uiApiResolutionRegistry);

export function getUiApiResolutionRecord(id: string): UiApiResolutionRecord | undefined {
  return uiApiResolutionRegistry[id];
}
