'use client';

import { useEffect } from 'react';
import { Badge, Button, Card, Modal } from '@/ui';
import { PDFViewer } from '@/components/documents/preview/viewers/PDFViewer';
import type { StatementBranding, StatementTemplate } from '@/types/distribution';
import { getStatementTemplateLabel } from './statement-template-constants';

export interface StatementPreviewModalProps {
  isOpen: boolean;
  onOpenChange: (open: boolean) => void;
  template: StatementTemplate;
  branding?: StatementBranding;
  distributionName: string;
  documentUrl?: string;
  documentName?: string;
}

export function StatementPreviewModal({
  isOpen,
  onOpenChange,
  template,
  branding,
  distributionName,
  documentUrl,
  documentName,
}: StatementPreviewModalProps) {
  useEffect(() => {
    if (!isOpen) return;
    const handleKeyDown = (event: KeyboardEvent) => {
      if (event.key === 'Escape') {
        onOpenChange(false);
      }
    };
    window.addEventListener('keydown', handleKeyDown);
    return () => window.removeEventListener('keydown', handleKeyDown);
  }, [isOpen, onOpenChange]);

  return (
    <Modal
      title="Statement Preview"
      isOpen={isOpen}
      onOpenChange={onOpenChange}
      size="full"
      isDismissable={false}
      className="statement-preview-modal"
      footer={(
        <div className="flex items-center justify-end gap-2">
          <Button variant="light" onPress={() => onOpenChange(false)}>
            Close
          </Button>
        </div>
      )}
    >
      <div className="grid gap-4 lg:grid-cols-[320px_1fr]">
        <Card padding="lg" className="space-y-3 text-sm">
          <div className="text-xs uppercase tracking-[0.2em] text-[var(--app-text-subtle)]">
            Statement
          </div>
          <div className="text-lg font-semibold">
            {documentName || distributionName}
          </div>
          <Badge size="sm" variant="flat">
            {getStatementTemplateLabel(template)}
          </Badge>
          <div className="text-[var(--app-text-muted)]">
            Branding preview for statements generated by the backend.
          </div>
          <div className="rounded-lg border border-[var(--app-border)] bg-[var(--app-surface)] p-4 text-xs text-[var(--app-text-muted)]">
            <div className="font-medium text-[var(--app-text)]">
              {branding?.companyName || 'Organization Name'}
            </div>
            <div className="mt-2 space-y-1">
              <div>Logo: {branding?.logo || 'None provided'}</div>
              <div>Footer: {branding?.footer || 'No footer configured'}</div>
              <div>Contact: {branding?.contactInfo || 'No contact info provided'}</div>
            </div>
          </div>
          <div className="text-xs text-[var(--app-text-subtle)]">
            Press Esc to close.
          </div>
        </Card>

        <Card padding="lg" className="flex min-h-[60vh] flex-col">
          {documentUrl ? (
            <div className="flex-1 overflow-hidden rounded-lg border border-[var(--app-border)]">
              <PDFViewer url={documentUrl} />
            </div>
          ) : (
            <div className="flex flex-1 items-center justify-center rounded-lg border border-dashed border-[var(--app-border)] text-center text-xs text-[var(--app-text-muted)]">
              PDF preview will appear once a statement is generated.
            </div>
          )}
        </Card>
      </div>
    </Modal>
  );
}
