'use client';

import { Badge, Button, Card, Modal } from '@/ui';
import { PDFViewer } from '@/components/documents/preview/viewers/PDFViewer';
import type { StatementBranding, StatementTemplate } from '@/types/distribution';
import { getStatementTemplateLabel } from './statement-template-constants';

export interface StatementPreviewModalProps {
  isOpen: boolean;
  onOpenChange: (open: boolean) => void;
  template: StatementTemplate;
  branding?: StatementBranding;
  distributionName: string;
  documentUrl?: string;
  documentName?: string;
}

export function StatementPreviewModal({
  isOpen,
  onOpenChange,
  template,
  branding,
  distributionName,
  documentUrl,
  documentName,
}: StatementPreviewModalProps) {
  return (
    <Modal
      title="Statement Preview"
      isOpen={isOpen}
      onOpenChange={onOpenChange}
      footer={(
        <div className="flex items-center justify-end gap-2">
          <Button variant="light" onPress={() => onOpenChange(false)}>
            Close
          </Button>
        </div>
      )}
    >
      <Card padding="lg" className="space-y-3 text-sm">
        <div className="flex items-center justify-between">
          <div className="font-semibold">{documentName || distributionName}</div>
          <Badge size="sm" variant="flat">
            {getStatementTemplateLabel(template)}
          </Badge>
        </div>
        <div className="text-[var(--app-text-muted)]">
          Branding preview for statements generated by the backend.
        </div>
        <div className="rounded-lg border border-[var(--app-border)] bg-[var(--app-surface)] p-4 text-xs text-[var(--app-text-muted)]">
          <div className="font-medium text-[var(--app-text)]">
            {branding?.companyName || 'Organization Name'}
          </div>
          <div className="mt-2 space-y-1">
            <div>Logo: {branding?.logo || 'None provided'}</div>
            <div>Footer: {branding?.footer || 'No footer configured'}</div>
            <div>Contact: {branding?.contactInfo || 'No contact info provided'}</div>
          </div>
        </div>
        {documentUrl ? (
          <div className="h-[520px] overflow-hidden rounded-lg border border-[var(--app-border)]">
            <PDFViewer url={documentUrl} />
          </div>
        ) : (
          <div className="rounded-lg border border-dashed border-[var(--app-border)] p-6 text-center text-xs text-[var(--app-text-muted)]">
            PDF preview will appear once a statement is generated.
          </div>
        )}
      </Card>
    </Modal>
  );
}
